
export interface Option {
    label: string;
    value: string;
  }
  
  const chronic_diseasesOptions: Option[] = [
    { label: "No Disease", value: "no_Disease" },
    { label: "Alzheimer's Disease", value: "alzheimers_disease" },
    { label: "Arthritis", value: "arthritis" },
    { label: "Asthma", value: "asthma" },
    { label: "Cancer", value: "cancer" },
    { label: "Chronic Bronchitis", value: "chronic_bronchitis" },
    { label: "Chronic Fatigue Syndrome", value: "chronic_fatigue_syndrome" },
    { label: "Chronic Kidney Disease", value: "chronic_kidney_disease" },
    { label: "Chronic Obstructive Pulmonary Disease (COPD)", value: "copd" },
    { label: "Crohn's Disease", value: "crohns_disease" },
    { label: "Cystic Fibrosis", value: "cystic_fibrosis" },
    { label: "Diabetes", value: "diabetes" },
    { label: "Epilepsy", value: "epilepsy" },
    { label: "Fibromyalgia", value: "fibromyalgia" },
    { label: "Glaucoma", value: "glaucoma" },
    { label: "Gout", value: "gout" },
    { label: "Heart Disease", value: "heart_disease" },
    { label: "Hepatitis", value: "hepatitis" },
    { label: "Hypertension", value: "hypertension" },
    { label: "Hyperthyroidism", value: "hyperthyroidism" },
    { label: "Hypothyroidism", value: "hypothyroidism" },
    { label: "Inflammatory Bowel Disease", value: "inflammatory_bowel_disease" },
    { label: "Irritable Bowel Syndrome", value: "irritable_bowel_syndrome" },
    { label: "Kidney Disease", value: "kidney_disease" },
    { label: "Lupus", value: "lupus" },
    { label: "Multiple Sclerosis", value: "multiple_sclerosis" },
    { label: "Osteoarthritis", value: "osteoarthritis" },
    { label: "Parkinson's Disease", value: "parkinsons_disease" },
    { label: "Peptic Ulcer Disease", value: "peptic_ulcer_disease" },
    { label: "Pneumonia", value: "pneumonia" },
    { label: "Rheumatoid Arthritis", value: "rheumatoid_arthritis" },
    { label: "Sleep Apnea", value: "sleep_apnea" },
    { label: "Stroke", value: "stroke" },
    { label: "Tuberculosis", value: "tuberculosis" },
    { label: "Ulcerative Colitis", value: "ulcerative_colitis" },
    { label: "Anemia", value: "anemia" },
    { label: "Atrial Fibrillation", value: "atrial_fibrillation" },
    { label: "Bipolar Disorder", value: "bipolar_disorder" },
    { label: "Bradycardia", value: "bradycardia" },
    { label: "Chronic Sinusitis", value: "chronic_sinusitis" },
    { label: "Chronic Pain", value: "chronic_pain" },
    { label: "Cirrhosis", value: "cirrhosis" },
    { label: "Deep Vein Thrombosis", value: "deep_vein_thrombosis" },
    { label: "Dementia", value: "dementia" },
    { label: "Dyslipidemia", value: "dyslipidemia" },
    { label: "Endometriosis", value: "endometriosis" },
    { label: "Erectile Dysfunction", value: "erectile_dysfunction" },
    { label: "Epilepsy", value: "epilepsy" },
    { label: "Heart Failure", value: "heart_failure" },
    { label: "HIV/AIDS", value: "hiv_aids" },
    { label: "Hypoglycemia", value: "hypoglycemia" },
    { label: "Liver Disease", value: "liver_disease" },
    { label: "Lung Cancer", value: "lung_cancer" },
    { label: "Menopause", value: "menopause" },
    { label: "Mental Health Disorder", value: "mental_health_disorder" },
    { label: "Migraine", value: "migraine" },
    { label: "Osteoporosis", value: "osteoporosis" },
    { label: "Peptic Ulcer", value: "peptic_ulcer" },
    { label: "Post-traumatic Stress Disorder (PTSD)", value: "ptsd" },
    { label: "Panic Disorder", value: "panic_disorder" },
    { label: "Psoriasis", value: "psoriasis" },
    { label: "Schizophrenia", value: "schizophrenia" },
    { label: "Sickle Cell Disease", value: "sickle_cell_disease" },
    { label: "Sleep Disorder", value: "sleep_disorder" },
    { label: "Thyroid Disease", value: "thyroid_disease" },
    { label: "Tuberculosis", value: "tuberculosis" },
    { label: "Urinary Tract Infection", value: "urinary_tract_infection" },
    { label: "Venous Insufficiency", value: "venous_insufficiency" },
    { label: "Vertigo", value: "vertigo" },
    { label: "Viral Infections", value: "viral_infections" },
    { label: "Wegener's Granulomatosis", value: "wegener_granulomatosis" },
    { label: "Whiplash", value: "whiplash" },
    { label: "Wounds and Ulcers", value: "wounds_ulcers" },
    { label: "Addison's Disease", value: "addisons_disease" },
    { label: "Amputation", value: "amputation" },
    { label: "Anxiety", value: "anxiety" },
    { label: "Asthma", value: "asthma" },
    { label: "Autism Spectrum Disorder", value: "autism_spectrum_disorder" },
    { label: "Bacterial Infection", value: "bacterial_infection" },
    { label: "Bell's Palsy", value: "bells_palsy" },
    { label: "Bladder Cancer", value: "bladder_cancer" },
    { label: "Bladder Infection", value: "bladder_infection" },
    { label: "Brain Tumor", value: "brain_tumor" },
    { label: "Bursitis", value: "bursitis" },
    { label: "Celiac Disease", value: "celiac_disease" },
    { label: "Chronic Depression", value: "chronic_depression" },
    { label: "Chronic Fatigue Syndrome", value: "chronic_fatigue_syndrome" },
    { label: "Chronic Liver Disease", value: "chronic_liver_disease" },
    { label: "Chronic Stress", value: "chronic_stress" },
    { label: "Cognitive Decline", value: "cognitive_decline" },
    { label: "Colorectal Cancer", value: "colorectal_cancer" },
    { label: "Congestive Heart Failure", value: "congestive_heart_failure" },
    { label: "Coronary Artery Disease", value: "coronary_artery_disease" },
    { label: "Crohn's Disease", value: "crohns_disease" },
    { label: "Cystic Fibrosis", value: "cystic_fibrosis" },
    { label: "Diabetic Retinopathy", value: "diabetic_retinopathy" },
    { label: "Dialysis", value: "dialysis" },
    { label: "Diverticulitis", value: "diverticulitis" },
    { label: "End-Stage Renal Disease", value: "end_stage_renal_disease" },
    { label: "Fertility Issues", value: "fertility_issues" },
    { label: "Heart Valve Disease", value: "heart_valve_disease" },
    { label: "Hodgkin's Lymphoma", value: "hodgkins_lymphoma" },
    { label: "Incontinence", value: "incontinence" },
    { label: "Influenza", value: "influenza" },
    { label: "Liver Cirrhosis", value: "liver_cirrhosis" },
    { label: "Lupus Erythematosus", value: "lupus_erythematosus" },
    { label: "Mental Health Issues", value: "mental_health_issues" },
    { label: "Non-Hodgkin's Lymphoma", value: "non_hodgkins_lymphoma" },
    { label: "Osteomalacia", value: "osteomalacia" },
    { label: "Pancreatitis", value: "pancreatitis" },
    { label: "Peripheral Artery Disease", value: "peripheral_artery_disease" },
    { label: "Prostate Cancer", value: "prostate_cancer" },
    { label: "Pulmonary Hypertension", value: "pulmonary_hypertension" },
    { label: "Restless Leg Syndrome", value: "restless_leg_syndrome" },
    { label: "Scoliosis", value: "scoliosis" },
    { label: "Sleep Apnea", value: "sleep_apnea" },
    { label: "Spinal Cord Injury", value: "spinal_cord_injury" },
    { label: "Systemic Lupus Erythematosus", value: "systemic_lupus_erythematosus" },
    { label: "Thyroid Cancer", value: "thyroid_cancer" },
    { label: "Trigeminal Neuralgia", value: "trigeminal_neuralgia" },
    { label: "Tuberculosis", value: "tuberculosis" },
    { label: "Urinary Retention", value: "urinary_retention" },
    { label: "Uterine Cancer", value: "uterine_cancer" },
    { label: "Vaginal Infections", value: "vaginal_infections" },
    { label: "Viral Hepatitis", value: "viral_hepatitis" },
    { label: "Warts", value: "warts" },
  ];
  const allergiesOptions: Option[] = [
    { label: "No Allergies", value: "no_allergies" },
    { label: "Pollen", value: "pollen" },
    { label: "Dust", value: "dust" },
    { label: "Pet Dander", value: "pet_dander" },
    { label: "Mold", value: "mold" },
    { label: "Food Allergies", value: "food_allergies" },
    { label: "Peanuts", value: "peanuts" },
    { label: "Tree Nuts", value: "tree_nuts" },
    { label: "Shellfish", value: "shellfish" },
    { label: "Eggs", value: "eggs" },
    { label: "Milk", value: "milk" },
    { label: "Wheat", value: "wheat" },
    { label: "Soy", value: "soy" },
    { label: "Fish", value: "fish" },
    { label: "Latex", value: "latex" },
    { label: "Insect Stings", value: "insect_stings" },
    { label: "Bee Stings", value: "bee_stings" },
    { label: "Wasp Stings", value: "wasp_stings" },
    { label: "Ant Stings", value: "ant_stings" },
    { label: "Medicine Allergies", value: "medicine_allergies" },
    { label: "Aspirin", value: "aspirin" },
    { label: "Penicillin", value: "penicillin" },
    { label: "Sulfa Drugs", value: "sulfa_drugs" },
    { label: "Ibuprofen", value: "ibuprofen" },
    { label: "Lidocaine", value: "lidocaine" },
    { label: "Corticosteroids", value: "corticosteroids" },
    { label: "Antibiotics", value: "antibiotics" },
    { label: "Vaccines", value: "vaccines" },
    { label: "Topical Agents", value: "topical_agents" },
    { label: "Nuts", value: "nuts" },
    { label: "Chocolate", value: "chocolate" },
    { label: "Citrus Fruits", value: "citrus_fruits" },
    { label: "Bananas", value: "bananas" },
    { label: "Tomatoes", value: "tomatoes" },
    { label: "Strawberries", value: "strawberries" },
    { label: "Avocado", value: "avocado" },
    { label: "Kiwi", value: "kiwi" },
    { label: "Pineapple", value: "pineapple" },
    { label: "Apples", value: "apples" },
    { label: "Carrots", value: "carrots" },
    { label: "Celery", value: "celery" },
    { label: "Garlic", value: "garlic" },
    { label: "Onions", value: "onions" },
    { label: "Peas", value: "peas" },
    { label: "Cherries", value: "cherries" },
    { label: "Grapes", value: "grapes" },
    { label: "Plums", value: "plums" },
    { label: "Peaches", value: "peaches" },
    { label: "Melons", value: "melons" },
    { label: "Coconut", value: "coconut" },
    { label: "Mustard", value: "mustard" },
    { label: "Spices", value: "spices" },
    { label: "Cinnamon", value: "cinnamon" },
    { label: "Cloves", value: "cloves" },
    { label: "Pepper", value: "pepper" },
    { label: "Paprika", value: "paprika" },
    { label: "Anise", value: "anise" },
    { label: "Oregano", value: "oregano" },
    { label: "Thyme", value: "thyme" },
    { label: "Sage", value: "sage" },
    { label: "Rosemary", value: "rosemary" },
    { label: "Basil", value: "basil" },
    { label: "Mint", value: "mint" },
    { label: "Chamomile", value: "chamomile" },
    { label: "Lavender", value: "lavender" },
    { label: "Eucalyptus", value: "eucalyptus" },
    { label: "Tea Tree Oil", value: "tea_tree_oil" },
    { label: "Lemon Balm", value: "lemon_balm" },
    { label: "Marijuana", value: "marijuana" },
    { label: "Aloe Vera", value: "aloe_vera" },
    { label: "Sulfites", value: "sulfites" },
    { label: "Formaldehyde", value: "formaldehyde" },
    { label: "Fragrances", value: "fragrances" },
    { label: "Perfumes", value: "perfumes" },
    { label: "Cleaning Products", value: "cleaning_products" },
    { label: "Air Fresheners", value: "air_fresheners" },
    { label: "Paints", value: "paints" },
    { label: "Solvents", value: "solvents" },
    { label: "Chemicals", value: "chemicals" },
    { label: "Pollens", value: "pollens" },
    { label: "Fabrics", value: "fabrics" },
    { label: "Cotton", value: "cotton" },
    { label: "Polyester", value: "polyester" },
    { label: "Wool", value: "wool" },
    { label: "Silk", value: "silk" },
    { label: "Linen", value: "linen" },
    { label: "Leather", value: "leather" },
    { label: "Nylon", value: "nylon" },
    { label: "Rubber", value: "rubber" },
    { label: "Plastic", value: "plastic" },
    { label: "Gum", value: "gum" },
    { label: "Wood", value: "wood" },
    { label: "Hair Dye", value: "hair_dye" },
    { label: "Nickel", value: "nickel" },
    { label: "Copper", value: "copper" },
    { label: "Gold", value: "gold" },
    { label: "Silver", value: "silver" },
    { label: "Mercury", value: "mercury" },
    { label: "Lead", value: "lead" },
    { label: "Zinc", value: "zinc" },
    { label: "Benzene", value: "benzene" },
    { label: "Chlorine", value: "chlorine" },
    { label: "Ammonia", value: "ammonia" },
    { label: "Hydrogen Peroxide", value: "hydrogen_peroxide" },
    { label: "Formaldehyde", value: "formaldehyde" },
    { label: "Radon", value: "radon" },
    { label: "Asbestos", value: "asbestos" },
    { label: "Coal Dust", value: "coal_dust" },
    { label: "Pesticides", value: "pesticides" },
    { label: "Herbicides", value: "herbicides" },
    { label: "Fertilizers", value: "fertilizers" },
  ];
  
  const medicationOptions: Option[] = [
    { label: "Acetaminophen (Tylenol)", value: "acetaminophen_tylenol" },
    { label: "Ibuprofen (Advil, Motrin)", value: "ibuprofen_advil_motrin" },
    { label: "Aspirin", value: "aspirin" },
    { label: "Amoxicillin", value: "amoxicillin" },
    { label: "Azithromycin", value: "azithromycin" },
    { label: "Lisinopril", value: "lisinopril" },
    { label: "Metformin", value: "metformin" },
    { label: "Simvastatin", value: "simvastatin" },
    { label: "Hydrochlorothiazide", value: "hydrochlorothiazide" },
    { label: "Albuterol", value: "albuterol" },
    { label: "Omeprazole", value: "omeprazole" },
    { label: "Furosemide", value: "furosemide" },
    { label: "Gabapentin", value: "gabapentin" },
    { label: "Levothyroxine", value: "levothyroxine" },
    { label: "Prednisone", value: "prednisone" },
    { label: "Losartan", value: "losartan" },
    { label: "Atorvastatin", value: "atorvastatin" },
    { label: "Clopidogrel", value: "clopidogrel" },
    { label: "Sertraline (Zoloft)", value: "sertraline_zoloft" },
    { label: "Amlodipine", value: "amlodipine" },
    { label: "Pantoprazole", value: "pantoprazole" },
    { label: "Warfarin", value: "warfarin" },
    { label: "Duloxetine (Cymbalta)", value: "duloxetine_cymbalta" },
    { label: "Metoprolol", value: "metoprolol" },
    { label: "Prednisolone", value: "prednisolone" },
    { label: "Tamsulosin", value: "tamsulosin" },
    { label: "Diphenhydramine (Benadryl)", value: "diphenhydramine_benadryl" },
    { label: "Lorazepam", value: "lorazepam" },
    { label: "Hydrocodone", value: "hydrocodone" },
    { label: "Tramadol", value: "tramadol" },
    { label: "Zolpidem", value: "zolpidem" },
    { label: "Cetirizine (Zyrtec)", value: "cetirizine_zyrtec" },
    { label: "Fluoxetine (Prozac)", value: "fluoxetine_prozac" },
    { label: "Ciprofloxacin", value: "ciprofloxacin" },
    { label: "Ranitidine (Zantac)", value: "ranitidine_zantac" },
    { label: "Bupropion", value: "bupropion" },
    { label: "Allopurinol", value: "allopurinol" },
    { label: "Propranolol", value: "propranolol" },
    { label: "Carvedilol", value: "carvedilol" },
    { label: "Trazodone", value: "trazodone" },
    { label: "Corticosteroids (hydrocortisone)", value: "corticosteroids_hydrocortisone" },
    { label: "Fentanyl", value: "fentanyl" },
    { label: "Methotrexate", value: "methotrexate" },
    { label: "Insulin", value: "insulin" },
    { label: "Cholestyramine", value: "cholestyramine" },
    { label: "Mupirocin", value: "mupirocin" },
    { label: "Clindamycin", value: "clindamycin" },
    { label: "Fluconazole", value: "fluconazole" },
    { label: "Loratadine (Claritin)", value: "loratadine_claritin" },
    { label: "Hydroxychloroquine", value: "hydroxychloroquine" },
    { label: "Benzonatate", value: "benzonatate" },
    { label: "Dexamethasone", value: "dexamethasone" },
    { label: "Candesartan", value: "candesartan" },
    { label: "Valacyclovir", value: "valacyclovir" },
    { label: "Methadone", value: "methadone" },
    { label: "Tamsulosin", value: "tamsulosin" },
    { label: "Levocetirizine (Xyzal)", value: "levocetirizine_xyzal" },
    { label: "Eliquis", value: "eliquis" },
    { label: "Tamoxifen", value: "tamoxifen" },
    { label: "Nitroglycerin", value: "nitroglycerin" },
    { label: "Baclofen", value: "baclofen" },
    { label: "Esomeprazole", value: "esomeprazole" },
    { label: "Buspirone", value: "buspirone" },
    { label: "Amoxicillin-Clavulanate", value: "amoxicillin_clavulanate" },
    { label: "Azathioprine", value: "azathioprine" },
    { label: "Ezetimibe", value: "ezetimibe" },
    { label: "Colchicine", value: "colchicine" },
    { label: "Doxycycline", value: "doxycycline" },
    { label: "Sildenafil (Viagra)", value: "sildenafil_viagra" },
    { label: "Zopiclone", value: "zopiclone" },
    { label: "Naproxen", value: "naproxen" },
    { label: "Ipratropium", value: "ipratropium" },
    { label: "Prazosin", value: "prazosin" },
    { label: "Raloxifene", value: "raloxifene" },
    { label: "Spironolactone", value: "spironolactone" },
    { label: "Naltrexone", value: "naltrexone" },
    { label: "Ondansetron", value: "ondansetron" },
    { label: "Ropinirole", value: "ropinirole" },
    { label: "Varenicline (Chantix)", value: "varenicline_chantix" },
    { label: "Cefdinir", value: "cefdinir" },
    { label: "Nimodipine", value: "nimodipine" },
    { label: "Ticagrelor", value: "ticagrelor" },
    { label: "Fluticasone", value: "fluticasone" },
    { label: "Terazosin", value: "terazosin" },
    { label: "Quetiapine", value: "quetiapine" },
    { label: "Risperidone", value: "risperidone" },
    { label: "Escitalopram", value: "escitalopram" },
    { label: "Mirtazapine", value: "mirtazapine" },
    { label: "Benzodiazepines (Valium, Xanax)", value: "benzodiazepines_valium_xanax" },
    { label: "Allopurinol", value: "allopurinol" },
    { label: "Tamsulosin", value: "tamsulosin" }
  ];
  const conditionStatusOptions: Option[]  = [
    { label: 'Don`t Know', value: 'Undefined' },
    { label: 'Treated', value: 'treated' },
    { label: 'Resolved', value: 'resolved' },
    { label: 'Managed', value: 'managed' },
    { label: 'In Recovery', value: 'in_recovery' },
    { label: 'Uncontrolled', value: 'uncontrolled' },
    { label: 'Stable', value: 'stable' },
    { label: 'Under Control', value: 'under_control' },
    { label: 'Improved', value: 'improved' },
    { label: 'Remission', value: 'remission' },
    { label: 'Worsened', value: 'worsened' },
    { label: 'Recurred', value: 'recurred' },
    { label: 'Progressing', value: 'progressing' },
    { label: 'Not Active', value: 'not_active' },
    { label: 'Exacerbated', value: 'exacerbated' },
    { label: 'Decompensated', value: 'decompensated' },
    { label: 'Recovered', value: 'recovered' },
    { label: 'Slightly Better', value: 'slightly_better' },
    { label: 'Comorbid', value: 'comorbid' },
    { label: 'Fluctuating', value: 'fluctuating' },
    { label: 'Surgical Treatment', value: 'surgical_treatment' },
    { label: 'Managed with Medication', value: 'managed_with_medication' },
    { label: 'Chronic', value: 'chronic' },
    { label: 'Acute', value: 'acute' },
    { label: 'Inactive', value: 'inactive' },
    { label: 'Controlled', value: 'controlled' },
    { label: 'Ongoing Treatment', value: 'ongoing_treatment' },
    { label: 'Partially Resolved', value: 'partially_resolved' },
    { label: 'Cured', value: 'cured' },
    { label: 'Terminal', value: 'terminal' },
    { label: 'Post-Treatment', value: 'post_treatment' },
    { label: 'Treating Symptoms', value: 'treating_symptoms' },
    { label: 'In Observation', value: 'in_observation' },
    { label: 'Under Investigation', value: 'under_investigation' },
    { label: 'Responding to Treatment', value: 'responding_to_treatment' },
    { label: 'No Longer Present', value: 'no_longer_present' },
    { label: 'Symptom-Free', value: 'symptom_free' },
    { label: 'Progressing with Therapy', value: 'progressing_with_therapy' },
    { label: 'Not Resolved', value: 'not_resolved' },
    { label: 'Recently Diagnosed', value: 'recently_diagnosed' },
    { label: 'In Remission', value: 'in_remission' },
    { label: 'Acute and Improving', value: 'acute_and_improving' },
    { label: 'Symptom Relief Achieved', value: 'symptom_relief_achieved' },
    { label: 'No Significant Change', value: 'no_significant_change' },
    { label: 'Not Managed', value: 'not_managed' },
    { label: 'On Hold', value: 'on_hold' },
    { label: 'Relapsing', value: 'relapsing' },
    { label: 'Responding to Lifestyle Changes', value: 'responding_to_lifestyle_changes' },
    { label: 'Not Improving', value: 'not_improving' },
    { label: 'At Risk', value: 'at_risk' },
    { label: 'Undergoing Testing', value: 'undergoing_testing' },
    { label: 'In Progress', value: 'in_progress' },
    { label: 'Severe', value: 'severe' },
    { label: 'Controlled with Therapy', value: 'controlled_with_therapy' },
    { label: 'Self-Managing', value: 'self_managing' },
  ];
  
  const surgeriesOptions: Option[]  = [
    { label: 'Appendectomy', value: 'appendectomy' },
    { label: 'Cholecystectomy', value: 'cholecystectomy' },
    { label: 'Hysterectomy', value: 'hysterectomy' },
    { label: 'Cataract Surgery', value: 'cataract_surgery' },
    { label: 'Knee Replacement', value: 'knee_replacement' },
    { label: 'Hip Replacement', value: 'hip_replacement' },
    { label: 'Coronary Artery Bypass', value: 'coronary_artery_bypass' },
    { label: 'Gallbladder Removal', value: 'gallbladder_removal' },
    { label: 'Spinal Fusion', value: 'spinal_fusion' },
    { label: 'Laparotomy', value: 'laparotomy' },
    { label: 'Bariatric Surgery', value: 'bariatric_surgery' },
    { label: 'Thyroidectomy', value: 'thyroidectomy' },
    { label: 'Mastectomy', value: 'mastectomy' },
    { label: 'Prostatectomy', value: 'prostatectomy' },
    { label: 'Nephrectomy', value: 'nephrectomy' },
    { label: 'Cesarean Section', value: 'cesarean_section' },
    { label: 'Tonsillectomy', value: 'tonsillectomy' },
    { label: 'Appendix Removal', value: 'appendix_removal' },
    { label: 'Fracture Repair', value: 'fracture_repair' },
    { label: 'Lung Biopsy', value: 'lung_biopsy' },
    { label: 'Kidney Stone Removal', value: 'kidney_stone_removal' },
    { label: 'Gallstone Removal', value: 'gallstone_removal' },
    { label: 'C-section', value: 'c_section' },
    { label: 'Hernia Repair', value: 'hernia_repair' },
    { label: 'Heart Valve Surgery', value: 'heart_valve_surgery' },
    { label: 'Cardiac Catheterization', value: 'cardiac_catheterization' },
    { label: 'Lung Surgery', value: 'lung_surgery' },
    { label: 'Breast Reconstruction', value: 'breast_reconstruction' },
    { label: 'Cardiothoracic Surgery', value: 'cardiothoracic_surgery' },
    { label: 'Ankle Surgery', value: 'ankle_surgery' },
    { label: 'Shoulder Surgery', value: 'shoulder_surgery' },
    { label: 'Hip Arthroscopy', value: 'hip_arthroscopy' },
    { label: 'Elbow Surgery', value: 'elbow_surgery' },
    { label: 'Facial Surgery', value: 'facial_surgery' },
    { label: 'Endoscopic Surgery', value: 'endoscopic_surgery' },
    { label: 'Neck Surgery', value: 'neck_surgery' },
    { label: 'Back Surgery', value: 'back_surgery' },
    { label: 'Liver Surgery', value: 'liver_surgery' },
    { label: 'Kidney Surgery', value: 'kidney_surgery' },
    { label: 'Pancreatic Surgery', value: 'pancreatic_surgery' },
    { label: 'Esophageal Surgery', value: 'esophageal_surgery' },
    { label: 'Eye Surgery', value: 'eye_surgery' },
    { label: 'Oral Surgery', value: 'oral_surgery' },
    { label: 'Chin Implant Surgery', value: 'chin_implant_surgery' },
    { label: 'Face Lift', value: 'face_lift' },
    { label: 'Liposuction', value: 'liposuction' },
    { label: 'Rhinoplasty', value: 'rhinoplasty' },
    { label: 'Tummy Tuck', value: 'tummy_tuck' },
    { label: 'Facial Reconstruction', value: 'facial_reconstruction' },
    { label: 'Breast Augmentation', value: 'breast_augmented' },
    { label: 'Botox Injections', value: 'botox_injections' },
    { label: 'Hair Transplant', value: 'hair_transplant' },
    { label: 'Dental Implants', value: 'dental_implants' },
    { label: 'Tissue Expansion Surgery', value: 'tissue_expansion_surgery' },
    { label: 'Liver Transplant', value: 'liver_transplant' },
    { label: 'Bone Marrow Transplant', value: 'bone_marrow_transplant' },
    { label: 'Organ Transplant', value: 'organ_transplant' },
    { label: 'Aortic Aneurysm Repair', value: 'aortic_aneurysm_repair' },
    { label: 'Laparoscopic Surgery', value: 'laparoscopic_surgery' },
    { label: 'Bladder Surgery', value: 'bladder_surgery' },
    { label: 'Cervical Disc Surgery', value: 'cervical_disc_surgery' },
    { label: 'Shoulder Arthroscopy', value: 'shoulder_arthroscopy' },
    { label: 'Hip Replacement Revision', value: 'hip_replacement_revision' },
    { label: 'Colonoscopy', value: 'colonoscopy' },
    { label: 'Gastric Bypass', value: 'gastric_bypass' },
    { label: 'Small Bowel Resection', value: 'small_bowel_resection' },
    { label: 'Large Bowel Surgery', value: 'large_bowel_surgery' },
    { label: 'Colostomy', value: 'colostomy' },
    { label: 'Rectal Surgery', value: 'rectal_surgery' },
    { label: 'Vaginal Surgery', value: 'vaginal_surgery' },
    { label: 'Cranial Surgery', value: 'cranial_surgery' },
    { label: 'Hand Surgery', value: 'hand_surgery' },
    { label: 'Foot Surgery', value: 'foot_surgery' },
    { label: 'Wrist Surgery', value: 'wrist_surgery' },
    { label: 'Gastric Sleeve', value: 'gastric_sleeve' },
    { label: 'Appendix Surgery', value: 'appendix_surgery' },
    { label: 'Endovenous Laser Therapy', value: 'endovenous_laser_therapy' },
    { label: 'Chiropractic Surgery', value: 'chiropractic_surgery' },
    { label: 'Plastic Surgery', value: 'plastic_surgery' },
    { label: 'Liver Biopsy', value: 'liver_biopsy' },
    { label: 'Bladder Removal', value: 'bladder_removal' },
    { label: 'Peritoneal Dialysis', value: 'peritoneal_dialysis' },
    { label: 'Cystectomy', value: 'cystectomy' },
    { label: 'Vasectomy', value: 'vasectomy' },
    { label: 'Tubal Ligation', value: 'tubal_ligation' },
    { label: 'Endometrial Ablation', value: 'endometrial_ablation' },
    { label: 'Pelvic Floor Surgery', value: 'pelvic_floor_surgery' },
    { label: 'Abdominoplasty', value: 'abdominoplasty' },
    { label: 'Skin Grafting', value: 'skin_grafting' },
    { label: 'Bone Fracture Repair', value: 'bone_fracture_repair' },
    { label: 'Cleft Palate Surgery', value: 'cleft_palate_surgery' },
    { label: 'Hemorrhoidectomy', value: 'hemorrhoidectomy' },
    { label: 'Scoliosis Surgery', value: 'scoliosis_surgery' },
    { label: 'Bunion Surgery', value: 'bunion_surgery' },
    { label: 'Mole Removal', value: 'mole_removal' },
    { label: 'Surgical Drainage', value: 'surgical_drainage' },
    { label: 'Plastic Surgery for Burns', value: 'plastic_surgery_for_burns' },
    { label: 'Reconstructive Surgery', value: 'reconstructive_surgery' },
    { label: 'Limb Salvage Surgery', value: 'limb_salvage_surgery' },
    { label: 'Biliary Surgery', value: 'biliary_surgery' },
    { label: 'Ventriculoperitoneal Shunt', value: 'ventriculoperitoneal_shunt' },
    { label: 'Parotid Gland Surgery', value: 'parotid_gland_surgery' },
    { label: 'Pneumonectomy', value: 'pneumonectomy' },
    { label: 'Cholecystostomy', value: 'cholecystostomy' },
    { label: 'Neurostimulation Surgery', value: 'neurostimulation_surgery' },
    { label: 'Lymphedema Surgery', value: 'lymphedema_surgery' },
    { label: 'Craniotomy', value: 'craniotomy' },
    { label: 'Tracheostomy', value: 'tracheostomy' },
    { label: 'Ventricular Septal Defect Repair', value: 'ventricular_septal_defect_repair' },
    { label: 'Neurolysis', value: 'neurolysis' },
    { label: 'Laryngectomy', value: 'laryngectomy' },
    { label: 'Splenectomy', value: 'splenectomy' },
    { label: 'Endoscopic Sinus Surgery', value: 'endoscopic_sinus_surgery' },
    { label: 'Gastrectomy', value: 'gastrectomy' },
    { label: 'Retinal Surgery', value: 'retinal_surgery' }
  ];
  const surgeryOutcomes : Option[] = [
    { label: 'Successful', value: 'successful' },
    { label: 'Complications', value: 'complications' },
    { label: 'Infection', value: 'infection' },
    { label: 'Bleeding', value: 'bleeding' },
    { label: 'Pain', value: 'pain' },
    { label: 'Scarring', value: 'scarring' },
    { label: 'Recovery Delayed', value: 'recovery_delayed' },
    { label: 'Full Recovery', value: 'full_recovery' },
    { label: 'Partial Recovery', value: 'partial_recovery' },
    { label: 'Unsuccessful', value: 'unsuccessful' },
    { label: 'No Improvement', value: 'no_improvement' },
    { label: 'Improvement', value: 'improvement' },
    { label: 'Chronic Pain', value: 'chronic_pain' },
    { label: 'Rehabilitation Required', value: 'rehabilitation_required' },
    { label: 'Short-Term Pain Relief', value: 'short_term_pain_relief' },
    { label: 'Long-Term Pain Relief', value: 'long_term_pain_relief' },
    { label: 'Permanent Disability', value: 'permanent_disability' },
    { label: 'Death', value: 'death' },
    { label: 'Adverse Reaction to Anesthesia', value: 'adverse_reaction_anesthesia' },
    { label: 'Improved Mobility', value: 'improved_mobility' },
    { label: 'Improved Quality of Life', value: 'improved_quality_of_life' },
    { label: 'Functional Improvement', value: 'functional_improvement' },
    { label: 'No Change', value: 'no_change' },
    { label: 'Post-Surgical Care Complications', value: 'post_surgical_care_complications' },
    { label: 'Wound Healing Issues', value: 'wound_healing_issues' },
    { label: 'Psychological Impact', value: 'psychological_impact' },
    { label: 'Nerve Damage', value: 'nerve_damage' },
    { label: 'Recovery without Issues', value: 'recovery_without_issues' },
    { label: 'No Further Treatment Required', value: 'no_further_treatment_required' },
    { label: 'Follow-Up Care Required', value: 'follow_up_care_required' },
    { label: 'Physical Therapy Required', value: 'physical_therapy_required' },
    { label: 'Surgical Site Infection', value: 'surgical_site_infection' },
    { label: 'Reoperation Required', value: 'reoperation_required' },
    { label: 'Improved Functionality', value: 'improved_functionality' },
    { label: 'Partial Functional Recovery', value: 'partial_functional_recovery' },
    { label: 'Full Functional Recovery', value: 'full_functional_recovery' },
    { label: 'No Improvement in Functionality', value: 'no_improvement_in_functionality' },
    { label: 'Short-Term Side Effects', value: 'short_term_side_effects' },
    { label: 'Long-Term Side Effects', value: 'long_term_side_effects' },
    { label: 'Surgical Outcome as Expected', value: 'surgical_outcome_as_expected' },
    { label: 'Surgical Outcome Worse than Expected', value: 'surgical_outcome_worse_than_expected' },
    { label: 'No Post-Surgical Complications', value: 'no_post_surgical_complications' },
    { label: 'Mild Complications', value: 'mild_complications' },
    { label: 'Severe Complications', value: 'severe_complications' },
    { label: 'Satisfactory Outcome', value: 'satisfactory_outcome' },
    { label: 'Dissatisfactory Outcome', value: 'dissatisfactory_outcome' },
    { label: 'Unexpected Outcome', value: 'unexpected_outcome' },
    { label: 'Improvement in Symptoms', value: 'improvement_in_symptoms' },
    { label: 'Decline in Symptoms', value: 'decline_in_symptoms' },
    { label: 'No Change in Symptoms', value: 'no_change_in_symptoms' },
    { label: 'Post-Operative Complications', value: 'post_operate_complications' },
    { label: 'Surgical Repair Failure', value: 'surgical_repair_failure' },
    { label: 'Health Status Decline', value: 'health_status_decline' },
    { label: 'No Change in Health Status', value: 'no_change_in_health_status' },
    { label: 'Immediate Post-Op Complications', value: 'immediate_post_op_complications' },
    { label: 'Delayed Post-Op Complications', value: 'delayed_post_op_complications' },
    { label: 'Neurological Improvement', value: 'neurological_improvement' },
    { label: 'Neurological Decline', value: 'neurological_decline' },
    { label: 'Surgical Success', value: 'surgical_success' },
    { label: 'Post-Op Pain Management Success', value: 'post_op_pain_management_success' },
    { label: 'Post-Op Pain Management Failure', value: 'post_op_pain_management_failure' },
    { label: 'Psychological Recovery', value: 'psychological_recovery' },
    { label: 'Psychological Setback', value: 'psychological_setback' },
    { label: 'Physical Recovery', value: 'physical_recovery' },
    { label: 'Physical Setback', value: 'physical_setback' },
    { label: 'Increased Functionality', value: 'increased_functionality' },
    { label: 'Decreased Functionality', value: 'decreased_functionality' },
    { label: 'Failure to Achieve Desired Outcome', value: 'failure_to_achieve_desired_outcome' },
    { label: 'No Surgical Complications', value: 'no_surgical_complications' },
    { label: 'Surgical Success with Minor Issues', value: 'surgical_success_with_minor_issues' },
    { label: 'Temporary Disability', value: 'temporary_disability' },
    { label: 'Long-Term Disability', value: 'long_term_disability' },
    { label: 'Functional Recovery with Residual Pain', value: 'functional_recovery_with_residual_pain' },
    { label: 'No Post-Surgery Pain', value: 'no_post_surgery_pain' },
    { label: 'Post-Operative Fever', value: 'post_operational_fever' }
  ];
  
  const painLocations:Option[] = [
    { label: 'Surgical Site', value: 'surgical_site' },
    { label: 'Head', value: 'head' },
    { label: 'Neck', value: 'neck' },
    { label: 'Shoulder', value: 'shoulder' },
    { label: 'Arm', value: 'arm' },
    { label: 'Hand', value: 'hand' },
    { label: 'Chest', value: 'chest' },
    { label: 'Back', value: 'back' },
    { label: 'Upper Back', value: 'upper_back' },
    { label: 'Lower Back', value: 'lower_back' },
    { label: 'Abdomen', value: 'abdomen' },
    { label: 'Pelvis', value: 'pelvis' },
    { label: 'Hip', value: 'hip' },
    { label: 'Leg', value: 'leg' },
    { label: 'Thigh', value: 'thigh' },
    { label: 'Knee', value: 'knee' },
    { label: 'Ankle', value: 'ankle' },
    { label: 'Foot', value: 'foot' },
    { label: 'Groin', value: 'groin' },
    { label: 'Face', value: 'face' },
    { label: 'Eye', value: 'eye' },
    { label: 'Jaw', value: 'jaw' },
    { label: 'Ear', value: 'ear' },
    { label: 'Shoulder Blade', value: 'shoulder_blade' },
    { label: 'Side', value: 'side' },
    { label: 'Ribs', value: 'ribs' },
    { label: 'Buttocks', value: 'buttocks' },
    { label: 'Tailbone', value: 'tailbone' },
    { label: 'Groin Area', value: 'groin_area' },
    { label: 'Elbow', value: 'elbow' },
    { label: 'Forearm', value: 'forearm' },
    { label: 'Wrist', value: 'wrist' },
    { label: 'Hand Palm', value: 'hand_palm' },
    { label: 'Fingers', value: 'fingers' },
    { label: 'Toe', value: 'toe' },
    { label: 'Scalp', value: 'scalp' },
    { label: 'Neck Base', value: 'neck_base' },
    { label: 'Underarm', value: 'underarm' },
    { label: 'Inner Thigh', value: 'inner_thigh' },
    { label: 'Outer Thigh', value: 'outer_thigh' },
    { label: 'Shin', value: 'shin' },
    { label: 'Calf', value: 'calf' },
    { label: 'Heel', value: 'heel' },
    { label: 'Arch of Foot', value: 'arch_of_foot' },
    { label: 'Entire Body', value: 'entire_body' }
  ];
  const painLevels:Option[] = [
    { label: 'No Pain', value: 'no_pain' },
    { label: 'Mild Discomfort', value: 'mild_discomfort' },
    { label: 'Mild Pain', value: 'mild_pain' },
    { label: 'Moderate Pain', value: 'moderate_pain' },
    { label: 'Severe Pain', value: 'severe_pain' },
    { label: 'Very Severe Pain', value: 'very_severe_pain' },
    { label: 'Unbearable Pain', value: 'unbearable_pain' }
  ];
  const recentTestResults:Option[] = [
    { label: "Normal", value: "normal" },
    { label: "Abnormal", value: "abnormal" },
    { label: "Positive", value: "positive" },
    { label: "Negative", value: "negative" },
    { label: "Stable", value: "stable" },
    { label: "Improved", value: "improved" },
    { label: "Deteriorated", value: "deteriorated" },
    { label: "Pending", value: "pending" },
    { label: "No Change", value: "no_change" },
    { label: "Reactive", value: "reactive" },
    { label: "Non-Reactive", value: "non_reactive" },
    { label: "Elevated", value: "elevated" },
    { label: "Reduced", value: "reduced" },
    { label: "Borderline", value: "borderline" },
    { label: "Indeterminate", value: "indeterminate" },
    { label: "Unremarkable", value: "unremarkable" },
    { label: "Critical", value: "critical" },
    { label: "Low Risk", value: "low_risk" },
    { label: "High Risk", value: "high_risk" },
    { label: "Within Range", value: "within_range" },
    { label: "Out of Range", value: "out_of_range" },
    { label: "Mild", value: "mild" },
    { label: "Moderate", value: "moderate" },
    { label: "Severe", value: "severe" },
    { label: "Unstable", value: "unstable" },
    { label: "Controlled", value: "controlled" },
    { label: "Uncontrolled", value: "uncontrolled" },
    { label: "Benign", value: "benign" },
    { label: "Malignant", value: "malignant" },
    { label: "Inflammatory", value: "inflammatory" },
    { label: "Infectious", value: "infectious" },
    { label: "Congenital", value: "congenital" },
    { label: "Acquired", value: "acquired" },
    { label: "Chronic", value: "chronic" },
    { label: "Acute", value: "acute" },
    { label: "Suspected", value: "suspected" },
    { label: "Confirmed", value: "confirmed" },
    { label: "Negative for Pathology", value: "negative_pathology" },
    { label: "Positive for Pathology", value: "positive_pathology" },
    { label: "No Abnormalities Detected", value: "no_abnormalities" },
    { label: "Anomaly Detected", value: "anomaly_detected" },
    { label: "Significant Findings", value: "significant_findings" },
    { label: "Non-Specific", value: "non_specific" },
    { label: "Detailed Findings in Report", value: "detailed_findings" },
    { label: "Unfit", value: "unfit" },
    { label: "Fit for Procedure", value: "fit_procedure" },
    { label: "Requires Follow-Up", value: "requires_follow_up" },
    { label: "Further Investigation Needed", value: "further_investigation" },
    { label: "Clinically Correlated", value: "clinically_correlated" },
    { label: "Technical Artifact", value: "technical_artifact" },
    { label: "Insufficient Sample", value: "insufficient_sample" },
  ];
  
  const postSurgeryIssues:Option[] = [
    { label: "Mild Pain", value: "mild_pain" },
    { label: "Moderate Pain", value: "moderate_pain" },
    { label: "Severe Pain", value: "severe_pain" },
    { label: "Sharp Pain", value: "sharp_pain" },
    { label: "Dull Ache", value: "dull_ache" },
    { label: "Throbbing Pain", value: "throbbing_pain" },
    { label: "Burning Sensation", value: "burning_sensation" },
    { label: "Numbness", value: "numbness" },
    { label: "Tingling Sensation", value: "tingling_sensation" },
    { label: "Stiffness", value: "stiffness" },
    { label: "Swelling", value: "swelling" },
    { label: "Redness", value: "redness" },
    { label: "Bruising", value: "bruising" },
    { label: "Infection", value: "infection" },
    { label: "Discharge from Incision", value: "discharge" },
    { label: "Fever", value: "fever" },
    { label: "Chills", value: "chills" },
    { label: "Fatigue", value: "fatigue" },
    { label: "Dizziness", value: "dizziness" },
    { label: "Nausea", value: "nausea" },
    { label: "Vomiting", value: "vomiting" },
    { label: "Loss of Appetite", value: "loss_of_appetite" },
    { label: "Shortness of Breath", value: "shortness_of_breath" },
    { label: "Coughing", value: "coughing" },
    { label: "Constipation", value: "constipation" },
    { label: "Diarrhea", value: "diarrhea" },
    { label: "Difficulty Urinating", value: "difficulty_urinating" },
    { label: "Urinary Retention", value: "urinary_retention" },
    { label: "Difficulty Swallowing", value: "difficulty_swallowing" },
    { label: "Heart Palpitations", value: "heart_palpitations" },
    { label: "High Blood Pressure", value: "high_blood_pressure" },
    { label: "Low Blood Pressure", value: "low_blood_pressure" },
    { label: "Headache", value: "headache" },
    { label: "Insomnia", value: "insomnia" },
    { label: "Anxiety", value: "anxiety" },
    { label: "Depression", value: "depression" },
    { label: "Mood Swings", value: "mood_swings" },
    { label: "Memory Problems", value: "memory_problems" },
    { label: "Confusion", value: "confusion" },
    { label: "Severe Itching", value: "severe_itching" },
    { label: "Excessive Sweating", value: "excessive_sweating" },
    { label: "Hiccups", value: "hiccups" },
    { label: "Inability to Move the Limb", value: "inability_to_move" },
    { label: "Limited Range of Motion", value: "limited_range_of_motion" },
    { label: "Joint Pain", value: "joint_pain" },
    { label: "Muscle Weakness", value: "muscle_weakness" },
    { label: "Loss of Sensation", value: "loss_of_sensation" },
    { label: "Abdominal Distension", value: "abdominal_distension" },
    { label: "Wound Opening", value: "wound_opening" },
    { label: "Hematoma", value: "hematoma" },
    { label: "Severe Scarring", value: "severe_scarring" },
    { label: "Surgical Site Infection", value: "surgical_site_infection" },
    { label: "Postoperative Bleeding", value: "postoperative_bleeding" },
    { label: "Lung Collapse (Pneumothorax)", value: "lung_collapse" },
    { label: "Blood Clots", value: "blood_clots" },
    { label: "Deep Vein Thrombosis (DVT)", value: "dvt" },
    { label: "Pulmonary Embolism", value: "pulmonary_embolism" },
    { label: "Organ Dysfunction", value: "organ_dysfunction" },
    { label: "Dehydration", value: "dehydration" },
    { label: "Electrolyte Imbalance", value: "electrolyte_imbalance" },
    { label: "Delayed Healing", value: "delayed_healing" },
    { label: "Persistent Pain at Surgical Site", value: "persistent_pain" },
    { label: "Feeling of Tightness", value: "feeling_of_tightness" },
    { label: "Post-Surgical Anxiety", value: "post_surgical_anxiety" },
    { label: "Post-Surgical Stress", value: "post_surgical_stress" },
    { label: "Post-Surgical Emotional Distress", value: "post_surgical_emotional_distress" },
    { label: "Post-Surgical Infection Risk", value: "post_surgical_infection_risk" },
    { label: "Post-Surgical Complications", value: "post_surgical_complications" },
    { label: "Delayed Mobility", value: "delayed_mobility" },
    { label: "Post-Surgical Edema", value: "post_surgical_edema" },
    { label: "Post-Surgical Weakness", value: "post_surgical_weakness" },
    { label: "Delayed Return to Work", value: "delayed_return_to_work" }
];
const institutionOptions:Option[] = [
  { label: "Harvard University", value: "harvard_university" },
  { label: "Stanford University", value: "stanford_university" },
  { label: "Massachusetts Institute of Technology (MIT)", value: "mit" },
  { label: "University of California, Berkeley", value: "uc_berkeley" },
  { label: "California Institute of Technology (Caltech)", value: "caltech" },
  { label: "University of Cambridge", value: "university_of_cambridge" },
  { label: "University of Oxford", value: "university_of_oxford" },
  { label: "Princeton University", value: "princeton_university" },
  { label: "Columbia University", value: "columbia_university" },
  { label: "University of Chicago", value: "university_of_chicago" },
  { label: "Yale University", value: "yale_university" },
  { label: "University of Toronto", value: "university_of_toronto" },
  { label: "University College London (UCL)", value: "ucl" },
  { label: "ETH Zurich", value: "eth_zurich" },
  { label: "University of Michigan", value: "university_of_michigan" },
  { label: "University of Washington", value: "university_of_washington" },
  { label: "University of Edinburgh", value: "university_of_edinburgh" },
  { label: "Carnegie Mellon University", value: "carnegie_mellon_university" },
  { label: "Cornell University", value: "cornell_university" },
  { label: "University of Texas at Austin", value: "university_of_texas_austin" },
  { label: "University of Southern California (USC)", value: "usc" },
  { label: "University of Pennsylvania", value: "university_of_pennsylvania" },
  { label: "Johns Hopkins University", value: "johns_hopkins_university" },
  { label: "Duke University", value: "duke_university" },
  { label: "Northwestern University", value: "northwestern_university" },
  { label: "University of Melbourne", value: "university_of_melbourne" },
  { label: "Australian National University", value: "australian_national_university" },
  { label: "McGill University", value: "mcgill_university" },
  { label: "University of British Columbia", value: "university_of_british_columbia" },
  { label: "University of Sydney", value: "university_of_sydney" },
  { label: "National University of Singapore (NUS)", value: "nus" },
  { label: "Peking University", value: "peking_university" },
  { label: "Tsinghua University", value: "tsinghua_university" },
  { label: "University of Hong Kong (HKU)", value: "hku" },
  { label: "Seoul National University (SNU)", value: "snu" },
  { label: "University of Tokyo", value: "university_of_tokyo" },
  { label: "Kyoto University", value: "kyoto_university" },
  { label: "Indian Institute of Technology (IIT) Bombay", value: "iit_bombay" },
  { label: "Indian Institute of Technology (IIT) Delhi", value: "iit_delhi" },
  { label: "University of Munich (LMU)", value: "university_of_munich" },
  { label: "Heidelberg University", value: "heidelberg_university" },
  { label: "Ecole Polytechnique", value: "ecole_polytechnique" },
  { label: "Sorbonne University", value: "sorbonne_university" },
  { label: "Sciences Po", value: "sciences_po" },
  { label: "University of Amsterdam", value: "university_of_amsterdam" },
  { label: "University of Copenhagen", value: "university_of_copenhagen" },
  { label: "Stockholm University", value: "stockholm_university" },
  { label: "University of Helsinki", value: "university_of_helsinki" },
  { label: "University of Oslo", value: "university_of_oslo" },
  { label: "University of Auckland", value: "university_of_auckland" },
  { label: "University of Cape Town", value: "university_of_cape_town" },
  { label: "University of the Witwatersrand", value: "wits_university" },
  { label: "University of Buenos Aires", value: "university_of_buenos_aires" },
  { label: "Pontifical Catholic University of Chile", value: "puc_chile" },
  { label: "National Autonomous University of Mexico (UNAM)", value: "unam" },
  { label: "University of Sao Paulo", value: "university_of_sao_paulo" },
  { label: "University of Ibadan", value: "university_of_ibadan" },
  { label: "Makerere University", value: "makerere_university" },
  { label: "University of Nairobi", value: "university_of_nairobi" },
  { label: "Kenyatta University", value: "kenyatta_university" },
  { label: "University of Lagos", value: "university_of_lagos" },
  { label: "University of Ghana", value: "university_of_ghana" },
  { label: "University of Pretoria", value: "university_of_pretoria" },
  { label: "Ain Shams University", value: "ain_shams_university" },
  { label: "Cairo University", value: "cairo_university" },
  { label: "Al Azhar University", value: "al_azhar_university" },
];
const languageOptions: Option[] = [
  { label: 'English', value: 'english' },
  { label: 'Spanish', value: 'spanish' },
  { label: 'Mandarin Chinese', value: 'mandarin_chinese' },
  { label: 'Hindi', value: 'hindi' },
  { label: 'French', value: 'french' },
  { label: 'Arabic', value: 'arabic' },
  { label: 'Bengali', value: 'bengali' },
  { label: 'Russian', value: 'russian' },
  { label: 'Portuguese', value: 'portuguese' },
  { label: 'Urdu', value: 'urdu' },
  { label: 'Japanese', value: 'japanese' },
  { label: 'German', value: 'german' },
  { label: 'Korean', value: 'korean' },
  { label: 'Italian', value: 'italian' },
  { label: 'Turkish', value: 'turkish' },
  { label: 'Tamil', value: 'tamil' },
  { label: 'Telugu', value: 'telugu' },
  { label: 'Marathi', value: 'marathi' },
  { label: 'Gujarati', value: 'gujarati' },
  { label: 'Punjabi', value: 'punjabi' },
  { label: 'Vietnamese', value: 'vietnamese' },
  { label: 'Persian', value: 'persian' },
  { label: 'Thai', value: 'thai' },
  { label: 'Swahili', value: 'swahili' },
  { label: 'Malay', value: 'malay' },
  { label: 'Cantonese', value: 'cantonese' },
  { label: 'Hausa', value: 'hausa' },
  { label: 'Burmese', value: 'burmese' },
  { label: 'Amharic', value: 'amharic' },
  { label: 'Romanian', value: 'romanian' },
  { label: 'Polish', value: 'polish' },
  { label: 'Dutch', value: 'dutch' },
  { label: 'Greek', value: 'greek' },
  { label: 'Czech', value: 'czech' },
  { label: 'Hungarian', value: 'hungarian' },
  { label: 'Swedish', value: 'swedish' },
  { label: 'Finnish', value: 'finnish' },
  { label: 'Norwegian', value: 'norwegian' },
  { label: 'Danish', value: 'danish' },
  { label: 'Hebrew', value: 'hebrew' },
  { label: 'Slovak', value: 'slovak' },
  { label: 'Croatian', value: 'croatian' },
  { label: 'Bulgarian', value: 'bulgarian' },
  { label: 'Ukrainian', value: 'ukrainian' },
  { label: 'Malayalam', value: 'malayalam' },
  { label: 'Kannada', value: 'kannada' },
  { label: 'Sinhalese', value: 'sinhalese' },
  { label: 'Kazakh', value: 'kazakh' },
  { label: 'Uzbek', value: 'uzbek' },
  { label: 'Pashto', value: 'pashto' },
  { label: 'Zulu', value: 'zulu' },
  { label: 'Xhosa', value: 'xhosa' },
  { label: 'Afrikaans', value: 'afrikaans' },
  { label: 'Somali', value: 'somali' },
  { label: 'Igbo', value: 'igbo' },
  { label: 'Yoruba', value: 'yoruba' },
  { label: 'Maori', value: 'maori' },
  { label: 'Samoan', value: 'samoan' },
  { label: 'Tongan', value: 'tongan' },
  { label: 'Fijian', value: 'fijian' },
  { label: 'Haitian Creole', value: 'haitian_creole' },
  { label: 'Creole', value: 'creole' },
  { label: 'Lao', value: 'lao' },
  { label: 'Khmer', value: 'khmer' },
  { label: 'Mongolian', value: 'mongolian' },
  { label: 'Nepali', value: 'nepali' },
  { label: 'Tibetan', value: 'tibetan' },
  { label: 'Armenian', value: 'armenian' },
  { label: 'Georgian', value: 'georgian' },
  { label: 'Azerbaijani', value: 'azerbaijani' },
  { label: 'Albanian', value: 'albanian' },
  { label: 'Bosnian', value: 'bosnian' },
  { label: 'Macedonian', value: 'macedonian' },
  { label: 'Serbian', value: 'serbian' },
  { label: 'Latvian', value: 'latvian' },
  { label: 'Lithuanian', value: 'lithuanian' },
  { label: 'Estonian', value: 'estonian' },
  { label: 'Icelandic', value: 'icelandic' },
  { label: 'Gaelic', value: 'gaelic' },
  { label: 'Welsh', value: 'welsh' },
  { label: 'Irish', value: 'irish' },
  { label: 'Basque', value: 'basque' },
  { label: 'Catalan', value: 'catalan' },
  { label: 'Galician', value: 'galician' },
  { label: 'Quechua', value: 'quechua' },
  { label: 'Aymara', value: 'aymara' },
  { label: 'Guarani', value: 'guarani' },
  { label: 'Mapudungun', value: 'mapudungun' },
  { label: 'Nahuatl', value: 'nahuatl' },
  { label: 'Inuktitut', value: 'inuktitut' },
  { label: 'Ojibwe', value: 'ojibwe' },
  { label: 'Cherokee', value: 'cherokee' },
];


const currencies: Option[] = [
  { label: 'USD (US Dollar)', value: 'usd' },
  { label: 'EUR (Euro)', value: 'eur' },
  { label: 'INR (Indian Rupee)', value: 'inr' },
  { label: 'GBP (British Pound)', value: 'gbp' },
  { label: 'AUD (Australian Dollar)', value: 'aud' },
  { label: 'CAD (Canadian Dollar)', value: 'cad' },
  { label: 'JPY (Japanese Yen)', value: 'jpy' },
  { label: 'CNY (Chinese Yuan)', value: 'cny' },
  { label: 'AED (United Arab Emirates Dirham)', value: 'aed' },
  { label: 'SAR (Saudi Riyal)', value: 'sar' },
  { label: 'CHF (Swiss Franc)', value: 'chf' },
  { label: 'MXN (Mexican Peso)', value: 'mxn' },
  { label: 'BRL (Brazilian Real)', value: 'brl' },
  { label: 'RUB (Russian Ruble)', value: 'rub' },
  { label: 'ZAR (South African Rand)', value: 'zar' },
  { label: 'SEK (Swedish Krona)', value: 'sek' },
  { label: 'NOK (Norwegian Krone)', value: 'nok' },
  { label: 'DKK (Danish Krone)', value: 'dkk' },
  { label: 'PLN (Polish Zloty)', value: 'pln' },
  { label: 'HUF (Hungarian Forint)', value: 'huf' },
  { label: 'IDR (Indonesian Rupiah)', value: 'idr' },
  { label: 'THB (Thai Baht)', value: 'thb' },
  { label: 'SGD (Singapore Dollar)', value: 'sgd' },
  { label: 'MYR (Malaysian Ringgit)', value: 'myr' },
  { label: 'KRW (South Korean Won)', value: 'krw' },
  { label: 'VND (Vietnamese Dong)', value: 'vnd' },
  { label: 'PHP (Philippine Peso)', value: 'php' },
  { label: 'TRY (Turkish Lira)', value: 'try' },
  { label: 'ILS (Israeli New Shekel)', value: 'ils' },
  { label: 'CLP (Chilean Peso)', value: 'clp' },
  { label: 'COP (Colombian Peso)', value: 'cop' },
  { label: 'PEN (Peruvian Nuevo Sol)', value: 'pen' },
  { label: 'UYU (Uruguayan Peso)', value: 'uyu' },
  { label: 'EGP (Egyptian Pound)', value: 'egp' },
  { label: 'PKR (Pakistani Rupee)', value: 'pkr' },
  { label: 'KWD (Kuwaiti Dinar)', value: 'kwd' },
  { label: 'BHD (Bahraini Dinar)', value: 'bhd' },
  { label: 'OMR (Omani Rial)', value: 'omr' },
  { label: 'QAR (Qatari Rial)', value: 'qar' },
  { label: 'JOD (Jordanian Dinar)', value: 'jod' },
  { label: 'LKR (Sri Lankan Rupee)', value: 'lkr' },
  { label: 'BDT (Bangladeshi Taka)', value: 'bdt' },
  { label: 'AFN (Afghan Afghani)', value: 'afn' },
  { label: 'XOF (CFA Franc)', value: 'xof' },
  { label: 'MXV (Mexican Unidad de Inversion)', value: 'mxv' },
  { label: 'VEF (Venezuelan Bolívar)', value: 'vef' },
  { label: 'HNL (Honduran Lempira)', value: 'hnl' },
  { label: 'GHS (Ghanaian Cedi)', value: 'ghs' },
  { label: 'BAM (Bosnia and Herzegovina Convertible Mark)', value: 'bam' },
  { label: 'RSD (Serbian Dinar)', value: 'rsd' },
  { label: 'MKD (Macedonian Denar)', value: 'mkd' },
  { label: 'KZT (Kazakhstani Tenge)', value: 'kzt' },
  { label: 'UZS (Uzbekistani Som)', value: 'uzs' },
  { label: 'TJS (Tajikistani Somoni)', value: 'tjs' },
  { label: 'AZN (Azerbaijani Manat)', value: 'azn' },
  { label: 'AMD (Armenian Dram)', value: 'amd' },
  { label: 'GEL (Georgian Lari)', value: 'gel' },
  { label: 'MNT (Mongolian Tugrik)', value: 'mnt' },
  { label: 'LTL (Lithuanian Litas)', value: 'ltl' },
  { label: 'LVL (Latvian Lats)', value: 'lvl' },
  { label: 'EEK (Estonian Kroon)', value: 'eek' },
  { label: 'ISK (Icelandic Króna)', value: 'isk' },
  { label: 'RWF (Rwandan Franc)', value: 'rwf' },
  { label: 'UGX (Ugandan Shilling)', value: 'ugx' },
  { label: 'TZS (Tanzanian Shilling)', value: 'tzs' },
  { label: 'MWK (Malawian Kwacha)', value: 'mwk' },
  { label: 'ZMW (Zambian Kwacha)', value: 'zmw' },
  { label: 'MWK (Malawian Kwacha)', value: 'mwk' },
  { label: 'LSL (Lesotho Loti)', value: 'lsl' },
  { label: 'BBD (Barbadian Dollar)', value: 'bbd' },
  { label: 'CUP (Cuban Peso)', value: 'cup' },
  { label: 'JMD (Jamaican Dollar)', value: 'jmd' },
  { label: 'HTG (Haitian Gourde)', value: 'htg' },
  { label: 'AWG (Aruban Florin)', value: 'awg' },
  { label: 'SYP (Syrian Pound)', value: 'syp' },
  { label: 'SDG (Sudanese Pound)', value: 'sdg' },
  { label: 'DZD (Algerian Dinar)', value: 'dzd' },
  { label: 'MGA (Malagasy Ariary)', value: 'mga' },
  { label: 'KMF (Comorian Franc)', value: 'kmf' },
  { label: 'AFN (Afghan Afghani)', value: 'afn' },
  { label: 'ZWL (Zimbabwean Dollar)', value: 'zwl' },
  { label: 'MDL (Moldovan Leu)', value: 'mdl' },
  { label: 'NPR (Nepalese Rupee)', value: 'npr' },
  { label: 'SLL (Sierra Leone Leone)', value: 'sll' },
  { label: 'XPF (CFP Franc)', value: 'xpf' },
  { label: 'SBD (Solomon Islands Dollar)', value: 'sbd' },
  { label: 'TOP (Tongan Paʻanga)', value: 'top' },
  { label: 'FJD (Fijian Dollar)', value: 'fjd' },
  { label: 'PGK (Papua New Guinean Kina)', value: 'pgk' },
  { label: 'BWP (Botswana Pula)', value: 'bwp' },
  { label: 'GGP (Guernsey Pound)', value: 'ggp' },
  { label: 'STN (São Tomé and Príncipe dobra)', value: 'stn' },
  { label: 'ERN (Eritrean Nakfa)', value: 'ern' },
  { label: 'KID (Kiribati Dollar)', value: 'kid' },
];


 const licenseTypes: Option[] = [
  { label: "General Practitioner", value: "general_practitioner" },
  { label: "Cardiology Specialist", value: "cardiology_specialist" },
  { label: "Neurology Specialist", value: "neurology_specialist" },
  { label: "Dermatology Specialist", value: "dermatology_specialist" },
  { label: "Pediatrics Specialist", value: "pediatrics_specialist" },
  { label: "Orthopedic Specialist", value: "orthopedic_specialist" },
  { label: "Radiology Specialist", value: "radiology_specialist" },
  { label: "Psychiatry Specialist", value: "psychiatry_specialist" },
  { label: "Anesthesiology Specialist", value: "anesthesiology_specialist" },
  { label: "Oncology Specialist", value: "oncology_specialist" },
  { label: "Emergency Medicine Specialist", value: "emergency_medicine_specialist" },
  { label: "Endocrinology Specialist", value: "endocrinology_specialist" },
  { label: "Gastroenterology Specialist", value: "gastroenterology_specialist" },
  { label: "Hematology Specialist", value: "hematology_specialist" },
  { label: "Immunology Specialist", value: "immunology_specialist" },
  { label: "Nephrology Specialist", value: "nephrology_specialist" },
  { label: "Urology Specialist", value: "urology_specialist" },
  { label: "Pulmonology Specialist", value: "pulmonology_specialist" },
  { label: "Rheumatology Specialist", value: "rheumatology_specialist" },
  { label: "Ophthalmology Specialist", value: "ophthalmology_specialist" },
  { label: "Obstetrics and Gynecology Specialist", value: "obstetrics_gynecology_specialist" },
  { label: "Plastic Surgery Specialist", value: "plastic_surgery_specialist" },
  { label: "General Surgery Specialist", value: "general_surgery_specialist" },
  { label: "Vascular Surgery Specialist", value: "vascular_surgery_specialist" },
  { label: "Family Medicine Specialist", value: "family_medicine_specialist" },
  { label: "Sports Medicine Specialist", value: "sports_medicine_specialist" },
  { label: "Geriatrics Specialist", value: "geriatrics_specialist" },
  { label: "Infectious Disease Specialist", value: "infectious_disease_specialist" },
  { label: "Clinical Pharmacologist", value: "clinical_pharmacologist" },
  { label: "Occupational Medicine Specialist", value: "occupational_medicine_specialist" },
  { label: "Forensic Pathologist", value: "forensic_pathologist" },
  { label: "Pathology Specialist", value: "pathology_specialist" },
  { label: "Public Health Specialist", value: "public_health_specialist" },
  { label: "Rehabilitation Medicine Specialist", value: "rehabilitation_medicine_specialist" },
  { label: "Addiction Medicine Specialist", value: "addiction_medicine_specialist" },
  { label: "Sleep Medicine Specialist", value: "sleep_medicine_specialist" },
  { label: "Clinical Genetics Specialist", value: "clinical_genetics_specialist" },
  { label: "Clinical Neurophysiologist", value: "clinical_neurophysiologist" },
  { label: "Pain Management Specialist", value: "pain_management_specialist" },
  { label: "Critical Care Specialist", value: "critical_care_specialist" },
  { label: "Palliative Care Specialist", value: "palliative_care_specialist" },
  { label: "Transplant Specialist", value: "transplant_specialist" },
  { label: "Medical Microbiologist", value: "medical_microbiologist" },
  { label: "Nuclear Medicine Specialist", value: "nuclear_medicine_specialist" },
  { label: "Veterinary Medicine Specialist", value: "veterinary_medicine_specialist" },
  { label: "Architectural License", value: "architectural_license" },
  { label: "Civil Engineering License", value: "civil_engineering_license" },
  { label: "Mechanical Engineering License", value: "mechanical_engineering_license" },
  { label: "Electrical Engineering License", value: "electrical_engineering_license" },
  { label: "Chemical Engineering License", value: "chemical_engineering_license" },
  { label: "Software Engineering License", value: "software_engineering_license" },
  { label: "Environmental Engineering License", value: "environmental_engineering_license" },
  { label: "Certified Public Accountant", value: "certified_public_accountant" },
  { label: "Chartered Financial Analyst", value: "chartered_financial_analyst" },
  { label: "Certified Management Accountant", value: "certified_management_accountant" },
  { label: "Bar License (Lawyer)", value: "bar_license" },
  { label: "Real Estate Agent License", value: "real_estate_agent_license" },
  { label: "Real Estate Broker License", value: "real_estate_broker_license" },
  { label: "Insurance Agent License", value: "insurance_agent_license" },
  { label: "Teacher Certification", value: "teacher_certification" },
  { label: "Pilot License", value: "pilot_license" },
  { label: "Commercial Driver's License", value: "commercial_drivers_license" },
  { label: "Maritime License", value: "maritime_license" },
  { label: "Plumber License", value: "plumber_license" },
  { label: "Electrician License", value: "electrician_license" },
  { label: "Construction Contractor License", value: "construction_contractor_license" },
  { label: "Cosmetology License", value: "cosmetology_license" },
  { label: "Massage Therapist License", value: "massage_therapist_license" },
  { label: "Personal Trainer Certification", value: "personal_trainer_certification" },
  { label: "Fitness Instructor License", value: "fitness_instructor_license" },
  { label: "Pharmacist License", value: "pharmacist_license" },
  { label: "Dental Hygienist License", value: "dental_hygienist_license" },
  { label: "Social Worker License", value: "social_worker_license" },
  { label: "Licensed Marriage and Family Therapist", value: "licensed_marriage_family_therapist" },
  { label: "Licensed Clinical Counselor", value: "licensed_clinical_counselor" },
  { label: "Certified Information Systems Security Professional", value: "cissp" },
  { label: "Certified Ethical Hacker", value: "certified_ethical_hacker" },
  { label: "Data Scientist Certification", value: "data_scientist_certification" },
];

  
  export {chronic_diseasesOptions,allergiesOptions,medicationOptions, conditionStatusOptions,surgeriesOptions,surgeryOutcomes,painLocations,painLevels,recentTestResults,postSurgeryIssues,institutionOptions,languageOptions,currencies,licenseTypes}