import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Rubik } from 'next/font/google';
import AuthProvider from "./context/Authprovider";
import { Toaster } from "@/components/ui/toaster"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Import Rubik font with desired weights
const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // Select weights you want
  variable: '--font-rubik', // Use CSS variable for custom utility
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={rubik.variable}>
            <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
